### PR TITLE
Add support for Horizontal Rules

### LINKED ISSUE #22: Unknown error, `The method 'merge' was called on null.`
I'm experiencing an error occasionally when building a `MarkdownBody` widget. It appears to be related to setting style for inner `Text` widgets.

Here's the call stack provided when run with `flutter run -v`
<details><summary>Click to expand</summary><p>

```
[  +13 ms] [DEVICE LOG] 2018-01-05 02:37:23.460388-0700  localhost Runner[18834]: (Flutter) ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +5 ms] ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] [DEVICE LOG] 2018-01-05 02:37:23.465859-0700  localhost Runner[18834]: (Flutter) The following NoSuchMethodError was thrown building SimpleMarkdown:
[        ] [DEVICE LOG] 2018-01-05 02:37:23.465963-0700  localhost Runner[18834]: (Flutter) The method 'merge' was called on null.
[        ] The following NoSuchMethodError was thrown building SimpleMarkdown:
[        ] The method 'merge' was called on null.
[        ] [DEVICE LOG] 2018-01-05 02:37:23.466042-0700  localhost Runner[18834]: (Flutter) Receiver: null
[        ] [DEVICE LOG] 2018-01-05 02:37:23.466092-0700  localhost Runner[18834]: (Flutter) Tried calling: merge(null)
[        ] Receiver: null
[ +346 ms] [DEVICE LOG] 2018-01-05 02:37:23.813112-0700  localhost Runner[18834]: (Flutter)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.813236-0700  localhost Runner[18834]: (Flutter) When the exception was thrown, this was the stack:
[        ] When the exception was thrown, this was the stack:
[   +6 ms] [DEVICE LOG] 2018-01-05 02:37:23.819570-0700  localhost Runner[18834]: (Flutter) #0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.819843-0700  localhost Runner[18834]: (Flutter) #1      MarkdownBuilder.visitElementBefore (package:flutter_markdown/src/builder.dart:155:28)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.820028-0700  localhost Runner[18834]: (Flutter) #2      Element.accept (package:markdown/src/ast.dart:45:17)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.820202-0700  localhost Runner[18834]: (Flutter) #3      MarkdownBuilder.build (package:flutter_markdown/src/builder.dart:116:12)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.820387-0700  localhost Runner[18834]: (Flutter) #4      _MarkdownWidgetState._parseMarkdown (package:flutter_markdown/src/widget.dart:117:25)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.820771-0700  localhost Runner[18834]: (Flutter) #5      _MarkdownWidgetState.didChangeDependencies (package:flutter_markdown/src/widget.dart:86:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.821338-0700  localhost Runner[18834]: (Flutter) #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:12)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.821733-0700  localhost Runner[18834]: (Flutter) #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3577:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.822222-0700  localhost Runner[18834]: (Flutter) #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875:14)
[   +1 ms] [DEVICE LOG] 2018-01-05 02:37:23.822721-0700  localhost Runner[18834]: (Flutter) #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2678:12)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.823240-0700  localhost Runner[18834]: (Flutter) #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.823552-0700  localhost Runner[18834]: (Flutter) #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[   +1 ms] [DEVICE LOG] 2018-01-05 02:37:23.823839-0700  localhost Runner[18834]: (Flutter) #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3582:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.823968-0700  localhost Runner[18834]: (Flutter) #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3577:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.824380-0700  localhost Runner[18834]: (Flutter) #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2875:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.824772-0700  localhost Runner[18834]: (Flutter) #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2678:12)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.825289-0700  localhost Runner[18834]: (Flutter) #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4375:32)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.825684-0700  localhost Runner[18834]: (Flutter) #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4703:17)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.826070-0700  localhost Runner[18834]: (Flutter) #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.826633-0700  localhost Runner[18834]: (Flutter) #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[   +1 ms] [DEVICE LOG] 2018-01-05 02:37:23.826801-0700  localhost Runner[18834]: (Flutter) #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.826949-0700  localhost Runner[18834]: (Flutter) #21     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4317:32)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.827425-0700  localhost Runner[18834]: (Flutter) #22     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4703:17)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.827694-0700  localhost Runner[18834]: (Flutter) #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.827913-0700  localhost Runner[18834]: (Flutter) #24     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[   +2 ms] [DEVICE LOG] 2018-01-05 02:37:23.828489-0700  localhost Runner[18834]: (Flutter) #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.829379-0700  localhost Runner[18834]: (Flutter) #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.829718-0700  localhost Runner[18834]: (Flutter) #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.830209-0700  localhost Runner[18834]: (Flutter) #28     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.831159-0700  localhost Runner[18834]: (Flutter) #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.831926-0700  localhost Runner[18834]: (Flutter) #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.832276-0700  localhost Runner[18834]: (Flutter) #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[   +2 ms] [DEVICE LOG] 2018-01-05 02:37:23.832983-0700  localhost Runner[18834]: (Flutter) #32     StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.833270-0700  localhost Runner[18834]: (Flutter) #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.833616-0700  localhost Runner[18834]: (Flutter) #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[   +1 ms] [DEVICE LOG] 2018-01-05 02:37:23.834960-0700  localhost Runner[18834]: (Flutter) #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.835509-0700  localhost Runner[18834]: (Flutter) #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.836185-0700  localhost Runner[18834]: (Flutter) #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[   +2 ms] [DEVICE LOG] 2018-01-05 02:37:23.837766-0700  localhost Runner[18834]: (Flutter) #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.838076-0700  localhost Runner[18834]: (Flutter) #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[  +62 ms] [DEVICE LOG] 2018-01-05 02:37:23.838247-0700  localhost Runner[18834]: (Flutter) #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.838369-0700  localhost Runner[18834]: (Flutter) #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.838572-0700  localhost Runner[18834]: (Flutter) #42     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.838683-0700  localhost Runner[18834]: (Flutter) #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.838769-0700  localhost Runner[18834]: (Flutter) #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.838880-0700  localhost Runner[18834]: (Flutter) #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.839001-0700  localhost Runner[18834]: (Flutter) #46     StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.839761-0700  localhost Runner[18834]: (Flutter) #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[   +1 ms] [DEVICE LOG] 2018-01-05 02:37:23.840237-0700  localhost Runner[18834]: (Flutter) #48     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4317:32)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.840482-0700  localhost Runner[18834]: (Flutter) #49     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4703:17)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.840695-0700  localhost Runner[18834]: (Flutter) #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.841277-0700  localhost Runner[18834]: (Flutter) #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.842125-0700  localhost Runner[18834]: (Flutter) #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.842874-0700  localhost Runner[18834]: (Flutter) #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.843319-0700  localhost Runner[18834]: (Flutter) #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.843633-0700  localhost Runner[18834]: (Flutter) #55     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4317:32)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.843877-0700  localhost Runner[18834]: (Flutter) #56     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4703:17)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.844275-0700  localhost Runner[18834]: (Flutter) #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.844624-0700  localhost Runner[18834]: (Flutter) #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.844808-0700  localhost Runner[18834]: (Flutter) #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.845024-0700  localhost Runner[18834]: (Flutter) #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.845588-0700  localhost Runner[18834]: (Flutter) #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.845971-0700  localhost Runner[18834]: (Flutter) #62     StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.846255-0700  localhost Runner[18834]: (Flutter) #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.846554-0700  localhost Runner[18834]: (Flutter) #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.847479-0700  localhost Runner[18834]: (Flutter) #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.848327-0700  localhost Runner[18834]: (Flutter) #66     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.848718-0700  localhost Runner[18834]: (Flutter) #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.849148-0700  localhost Runner[18834]: (Flutter) #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.849622-0700  localhost Runner[18834]: (Flutter) #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.850009-0700  localhost Runner[18834]: (Flutter) #70     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.850265-0700  localhost Runner[18834]: (Flutter) #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.851390-0700  localhost Runner[18834]: (Flutter) #72     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:696:34)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.851778-0700  localhost Runner[18834]: (Flutter) #73     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:665:7)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.852368-0700  localhost Runner[18834]: (Flutter) #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.853211-0700  localhost Runner[18834]: (Flutter) #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.854875-0700  localhost Runner[18834]: (Flutter) #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.855493-0700  localhost Runner[18834]: (Flutter) #77     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.856253-0700  localhost Runner[18834]: (Flutter) #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.857261-0700  localhost Runner[18834]: (Flutter) #79     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.858432-0700  localhost Runner[18834]: (Flutter) #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.858861-0700  localhost Runner[18834]: (Flutter) #81     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4317:32)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.859188-0700  localhost Runner[18834]: (Flutter) #82     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4703:17)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.859346-0700  localhost Runner[18834]: (Flutter) #83     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:182:17)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.860017-0700  localhost Runner[18834]: (Flutter) #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.860583-0700  localhost Runner[18834]: (Flutter) #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.861449-0700  localhost Runner[18834]: (Flutter) #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.862157-0700  localhost Runner[18834]: (Flutter) #87     ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.862510-0700  localhost Runner[18834]: (Flutter) #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.862838-0700  localhost Runner[18834]: (Flutter) #89     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.864226-0700  localhost Runner[18834]: (Flutter) #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.865210-0700  localhost Runner[18834]: (Flutter) #91     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.866280-0700  localhost Runner[18834]: (Flutter) #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.868260-0700  localhost Runner[18834]: (Flutter) #93     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.869480-0700  localhost Runner[18834]: (Flutter) #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.869985-0700  localhost Runner[18834]: (Flutter) #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.870835-0700  localhost Runner[18834]: (Flutter) #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.871335-0700  localhost Runner[18834]: (Flutter) #97     StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.871535-0700  localhost Runner[18834]: (Flutter) #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.871711-0700  localhost Runner[18834]: (Flutter) #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.872112-0700  localhost Runner[18834]: (Flutter) #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[  +54 ms] [DEVICE LOG] 2018-01-05 02:37:23.872584-0700  localhost Runner[18834]: (Flutter) #101    StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.873234-0700  localhost Runner[18834]: (Flutter) #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.873484-0700  localhost Runner[18834]: (Flutter) #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.873666-0700  localhost Runner[18834]: (Flutter) #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.873828-0700  localhost Runner[18834]: (Flutter) #105    ProxyElement.update (package:flutter/src/widgets/framework.dart:3847:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.874301-0700  localhost Runner[18834]: (Flutter) #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.874802-0700  localhost Runner[18834]: (Flutter) #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.875060-0700  localhost Runner[18834]: (Flutter) #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.875209-0700  localhost Runner[18834]: (Flutter) #109    StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.875437-0700  localhost Runner[18834]: (Flutter) #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.875836-0700  localhost Runner[18834]: (Flutter) #111    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.876013-0700  localhost Runner[18834]: (Flutter) #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.876161-0700  localhost Runner[18834]: (Flutter) #113    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.876306-0700  localhost Runner[18834]: (Flutter) #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.876443-0700  localhost Runner[18834]: (Flutter) #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4595:14)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.876685-0700  localhost Runner[18834]: (Flutter) #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.876999-0700  localhost Runner[18834]: (Flutter) #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.877372-0700  localhost Runner[18834]: (Flutter) #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.877737-0700  localhost Runner[18834]: (Flutter) #119    StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.877897-0700  localhost Runner[18834]: (Flutter) #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.878018-0700  localhost Runner[18834]: (Flutter) #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.878245-0700  localhost Runner[18834]: (Flutter) #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.878514-0700  localhost Runner[18834]: (Flutter) #123    StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.878998-0700  localhost Runner[18834]: (Flutter) #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.879301-0700  localhost Runner[18834]: (Flutter) #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.879523-0700  localhost Runner[18834]: (Flutter) #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.879771-0700  localhost Runner[18834]: (Flutter) #127    StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.879890-0700  localhost Runner[18834]: (Flutter) #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.879998-0700  localhost Runner[18834]: (Flutter) #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.880220-0700  localhost Runner[18834]: (Flutter) #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.880593-0700  localhost Runner[18834]: (Flutter) #131    StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.880857-0700  localhost Runner[18834]: (Flutter) #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.881145-0700  localhost Runner[18834]: (Flutter) #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.881363-0700  localhost Runner[18834]: (Flutter) #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.881681-0700  localhost Runner[18834]: (Flutter) #135    StatelessElement.update (package:flutter/src/widgets/framework.dart:3662:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.882452-0700  localhost Runner[18834]: (Flutter) #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.882750-0700  localhost Runner[18834]: (Flutter) #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.883201-0700  localhost Runner[18834]: (Flutter) #138    Element.rebuild (package:flutter/src/widgets/framework.dart:3463:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.883442-0700  localhost Runner[18834]: (Flutter) #139    StatefulElement.update (package:flutter/src/widgets/framework.dart:3737:5)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.883795-0700  localhost Runner[18834]: (Flutter) #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2667:15)
[        ] [DEVICE LOG] 2018-01-05 02:37:23.884604-0700  localhost Runner[18834]: (Flutter) #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3613:16)
```

</p></details>
<br />

Output from `flutter doctor`:

```
 ~/G/hn_flutter   master ±  flutter doctor
[✓] Flutter (on Mac OS X 10.13.1 17B1003, locale en-US, channel master)
    • Flutter at /Users/dudeofawesome/Library/Developer/flutter
    • Framework revision 70b32e85a3 (12 days ago), 2017-12-22 14:58:53 -0800
    • Engine revision 7c126001d8
    • Tools Dart version 1.25.0-dev.11.0
    • Engine Dart version 2.0.0-edge.9e8a3e2d31621c1bdf6139d068e7898a2ac2ab5a

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.2)
    • Android SDK at /Users/dudeofawesome/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-26, build-tools 26.0.2
    • ANDROID_HOME = /Users/dudeofawesome/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.2, Build version 9C40b
    • ios-deploy 1.9.2
    • CocoaPods version 1.3.1

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected devices
    • iPhone X • 072375FC-E01B-417E-88FA-2D94A7DE6993 • ios • iOS 11.2 (simulator)
```

### PR DESCRIPTION
**Pull request by xqwzts**
Fixes #22 by adding `hr` to the list of block tags.

Creates a new Divider widget for hr elements.

### CODE REVIEW

**Comment by xqwzts** [comment]
I'm a bit iffy about this implementation, mainly:
`Divider` is a Material widget, so I didn't want to use it directly from the builder [which uses platform-agnostic widgets], and instead placed it in the stylesheet.

**Comment by xqwzts** [comment]
Replaced the `Divider` with a `BoxDecoration`, and used the top border to draw a divider.

**Comment by DaveShuckerow** [comment]
This is a nice fix.  Tests and we're good to go!

**Comment by xqwzts** [comment]
Added a simple test

**Comment by xqwzts** [comment]
I had added some tests to make sure horizontal rules only get created when they're on an empty line, but came to realize that's more of a test case for the markdown.dart parser than flutter_markdown, so reverted them with the latest commit.

Beyond the simple widget creation test that's in already, are there any other scenarios to test for?

**Comment by DaveShuckerow** [comment]
This change looks good to me as-is.

**Comment by xqwzts** [comment]
Thanks for the review, as always!

**Pull request merged**
