### PR TITLE
Downgraded flutter version to 1.17.0

### PR DESCRIPTION
**Pull request by AndroidNils**
## Package is hidden
Currently this package is hidden on pub.dev. You can't find `flutter_markdown`

image

## Min. Flutter Version is 1.17.1, but pub.dev runs with 1.17.0 

image

image

https://pub.dev/packages/flutter_markdown#-analysis-tab-

### CODE REVIEW

**Comment by domesticmouse** [comment]
@jonasfj @mit-mit Any particular reason why Pub is running a downlevel Flutter version? I can downgrade Flutter Markdown, but I figure we should really update Pub to the actual current stable release.

@AndroidNils thanks for the heads up. I'll get this fixed ASAP, one way or another

**Comment by mit-mit** [comment]
Deployments to pub.dev are costly. We're working on making them cheaper, but until then some lag is expected. I'd recommend downgrading the SDK requirement to 1.17.0.

**Comment by jonasfj** [comment]
We're doing a release today, that'll carry the latest version of Flutter.

**Comment by domesticmouse** [comment]
Hilariously I just pushed the downgrade. All good 😁

**Pull request merged**
