### PR TITLE
Fix range error (#342)

### PR DESCRIPTION
**Pull request by dreamzhu**

### CODE REVIEW

**Comment by dreamzhu** [comment]
@googlebot I signed it!

**Comment by dreamzhu** [comment]
@googlebot I signed it!

**Comment by kubaprzetakiewicz** [comment]
Can this PR be updated or should I resubmit with fixed CLA and tests?

**Comment by stuartmorgan** [comment]
Thanks for the contribution! flutter_markdown has been migrated to the [flutter/packages repository](https://github.com/flutter/packages) as part of an effort to consolidate our repositories, so this repository will be archived shortly. If you are still interested in moving froward with this change, please submit it as a new PR in that repository.

**Pull request closed without merging**
