### PR TITLE
Parsing image caption & alt

### PR DESCRIPTION
**Pull request by anggriyulio**
Refer to markdown image syntax https://daringfireball.net/projects/markdown/basics . 
Allow MarkdownImageBuilder widget function to parse image caption and alt.

### CODE REVIEW

**Comment by domesticmouse** [comment]
@anggriyulio Can you please sign the CLA?

**Comment by anggriyulio** [comment]
> @anggriyulio Can you please sign the CLA?

Done!

**Comment by anggriyulio** [comment]
@googlebot I signed it!

**Comment by domesticmouse** [comment]
I have no idea why the `analyze` and `test` tests are failing, but the travis tests are passing. Merging anyways. Thanks for the PR @anggriyulio!

**Pull request merged**
