### PR TITLE
Null safety migration

### PR DESCRIPTION
**Pull request by domesticmouse**
Start of null safety migration.

Fixes: https://github.com/flutter/flutter_markdown/issues/323

/cc @mjordan56 fyi

### CODE REVIEW

**Comment by domesticmouse** [comment]
Hey @mjordan56, this is my first stab at migrating to null safety. I have the example app working, but the tests are broken. Can you have a poke at this PR and tell me what you think?

**Comment by mjordan56** [comment]
D'oh! I was replying to the notifications email. @domesticmouse Here are the two email responses I sent.

## First email

I've been looking at PR #324, your null safety first attempt. I figured out what was failing in the link_test.dart tests. It's interesting to see how some of the code reacts to the null safety changes. I assume you did the "dart migrate" command to get these changes. I noticed at least one instance of a null safety change being redundant. I won't hurt anything but it wasn't necessary either. I'm looking at some of the other tests that are failing. I just started looking at the image_test.dart tests. At this point, this seems to be a MockHttpClient problem.

So, how do you want to coordinate our effort? I don't want to waste my time if you or others are already working on something. Also, how do you want to take fixes? I created a local branch in my fork with your PR. Do you want us to merge our changes into your PR? I haven't done this before but GitHub says this is doable.

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork

 https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

It looks like you have to grant permission to do this, which makes sense. I have a change for the link tests now if you want them.

## Second email

I've confirmed the image tests are failing due to a problem in utils/createMockImageHttpClient line 195.

  when(client.getUrl(any))
      .thenAnswer((_) => Future<io.HttpClientRequest>.value(request));

The mock closure "any" has a return type of Null. I'm not sure of the correct solution to fix this problem. I can figure it out but I thought you or @thisisamank might have more insight into Mockito and know how to fix this bug.

Anyhow, when I set the six image tests that fail to skip and with the fixes I have for the link tests, I'm able to successfully complete all of the tests with your PR. How would you like to proceed?

**Comment by domesticmouse** [comment]
Hey @mjordan56 and @tehprofessor I'm curious how we should move this forward. One option is to land this PR as is and use follow up PRs to fix up issues. The other is to close this out and land a new PR from @tehprofessor instead. Preferences?

**Comment by mjordan56** [comment]
Hi @domesticmouse I think the easiest, and IMHO the correct solution, is to set the skip parameter on the tests that aren't passing then check in this PR. Once your PR is checked in I and others can then work on fixing the tests that are currently being skipped. As I mentioned previously, I already have fixes for the failing link tests. I should also go through and turn back on the skipped tests that were waiting for fixes from the markdown package that have been fixed in the latest build.

Regarding the Mockito failures. I read the Mockito null safety README file. The README specifically states that passing null parameters is a violation of null safety. The flutter_markdown tests used the Mockito package as designed per null safety which included passing null parameters and other unsafe null practices. These tests need to be re-written or use a different technic for mocking HTTP server calls. No disrespect to @tehprofessor, but I'm not convinced commenting out the call to createMockImageHttpClient is correct. While it will avoid executing the Mockito method that passes a null parameter how is a mock image server request being made for the image tests? Is an image being returned to the test so the image links can be validated? I need to investigate this, but I don't see how this is possible. Maybe @tehprofessor can explain.

**Comment by mjordan56** [comment]
@domesticmouse and @tehprofessor. I was curious about the Mockito HTTP client fix that has been implemented. Reading through the code I believe I understand why this fixes the Mockito null parameter passing problem. I did not write these image tests or the MockHttpClient utilities so I might be missing some of the finer details of the code. But from what I see, by commenting out the call to createMockImageHttpClient the mock HTTP client is never created and an actual HTTP client is created. Here is the comment from the overrides.dart file:

```
/// This class facilitates overriding [HttpClient] with a mock implementation.
/// It should be extended by another class in client code with overrides
/// that construct a mock implementation. The implementation in this base class
/// defaults to the actual [HttpClient] implementation. For example:
```

From what I can tell, the old createMockImageHttpClient was mocking an HTTP client with the intent to stream the list of ints that begin on line 219 of utils.dart. I don't see anything in the image tests that look for or tries to compare against this know image array. @domesticmouse do you know who authored these image tests and created the mock image HTTP client? Maybe they could shed some light on this implementation.

**Comment by domesticmouse** [comment]
@mjordan56 okiday, I'm going to land this PR as is. Please feel free to raise new PRs to clean things up. I suspect a bunch of the places that are marked as nullable probably shouldn't be.

**Pull request merged**
