### PR TITLE
Release paperwork for v0.5.0

### PR DESCRIPTION
**Pull request by domesticmouse**
Fixes https://github.com/flutter/flutter_markdown/issues/293

### CODE REVIEW

**Comment by domesticmouse** [comment]
PTAL @mjordan56

**Review by mjordan56 — APPROVED** [review]
All of the changes look good to me.

**Comment by domesticmouse** [comment]
> It will be good to see this version of the package pushed to pub.dev.

I'll publish this to pub.dev after @mit-mit approves this PR. He's in Europe, so I'm guessing in about 12 hours or so. =)

**Comment by domesticmouse** [comment]
TBR: @mit-mit

**Pull request merged**
