### PR TITLE
Add stylesheet option listBulletPadding

### PR DESCRIPTION
**Pull request by MarkusWendorf**
This PR adds the stylesheet option `listBulletPadding` as requested by https://github.com/flutter/flutter_markdown/issues/254.

Just now I stumbled upon this PR https://github.com/flutter/flutter_markdown/pull/301, which tries to achieve the same thing. 
I would prefer the addition to the stylesheet type this PR provides: 

`MarkdownStyleSheet(listBulletPadding: EdgeInsets.only(right: 8));`

### CODE REVIEW

**Comment by domesticmouse** [comment]
As per my comment on #301, I'd like to see an agreement on API design, and tests for the new API surface. Thanks!

**Review by domesticmouse — CHANGES_REQUESTED** [review]
Needs testing, and de-contesting with #301

**Comment by quiverware** [comment]
@domesticmouse I've reviewed this PR and PR #301. Both PRs address providing additional layout control of the Markdown list through adjusting the padding around the leading bullet, order number, or checkbox of the respective list type. The change proposed by @MarkusWendorf is consistent with the current code implementation. I tested the PR and reviewed the code and as far as I can tell, the code change works as intended. Regarding the competing PRs, #301 and #306, this pull request works and has an appropriate unit test whereas #301 appears to be incomplete. My vote is for PR #306 to be accepted and PR #301 to be rejected.

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
@quiverware @mjordan56 thank you for your reviews.

**Pull request merged**
