### PR TITLE
Update Cirrus and Travis to enforce stable.

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by mit-mit** [comment]
Are you sure you don't want both? Stable to ensure it works with what customers have, and master to catch regressions before stable is baked?

**Comment by domesticmouse** [comment]
I’m happy to have stable and beta as submit blocking. I’m not totally sold on master and/or dev being submit blocking. Is there a way to set it up for dev/master tests to be advisory only?

**Comment by domesticmouse** [comment]
Hey @RedBrogdon any suggestions on how to properly test for stable/beta/dev/master?

**Comment by domesticmouse** [comment]
I've put the work of testing this against multiple branches into a self assigned backlog ticket so I can land this as is.

**Pull request merged**
