### PR TITLE
Add support for render tags by user

### LINKED ISSUE #144: Add ability to render certain tags ourselves
I would like to be passed a Markdown "element" if I choose for rendering myself. Sometimes the stylesheet isn't enough. For example, I want to use a Flutter Widget that includes syntax highlighting for dart. I tried using their syntax highlighter class with this library, but it was riddled with errors. If we have a parameter for that, it would add a lot of flexibility. Or if the code for rendering each element was broken out into individual overridable functions for those extending the class, we could effectively accomplish the same thing

### PR DESCRIPTION
**Pull request by KagurazakaHanabi**
Closes #144

### CODE REVIEW

**Comment by vHanda** [comment]
ping?

Could someone please review this? I'll be happy to fix the failing tests, and rebase it. But I'd like to know if the proposed changes are acceptable.

**Comment by domesticmouse** [comment]
I'll happily review once the conflicts are fixed and the tests work.

**Comment by nobuhito** [comment]
I have resolved the conflicts and tests. I've also added test cases and fixed some minor bugs. What action should be taken?

**Comment by domesticmouse** [comment]
@nobuhito I need it in a PR with all the contributors have signed the CLA.

**Comment by nobuhito** [comment]
@KagurazakaHanabi  If I were to create a PR, which repository would be better?
KagurazakaHanabi/flutter_markdwon and flutter/flutter_markdown.

**Comment by vHanda** [comment]
> @KagurazakaHanabi If I were to create a PR, which repository would be better?
> KagurazakaHanabi/flutter_markdwon and flutter/flutter_markdown.

Ping. I think flutter/flutter_markdown would be better

**Comment by nobuhito** [comment]
A new PR has been created. #240

**Comment by domesticmouse** [comment]
Closing this PR due to https://github.com/flutter/flutter_markdown/pull/241 landing

**Pull request closed without merging**
