### PR TITLE
Fix user defined builders

### PR DESCRIPTION
**Pull request by MarkusWendorf**
Fixes https://github.com/flutter/flutter_markdown/issues/262
Original PR for feature: https://github.com/flutter/flutter_markdown/pull/241

Hey there,

I tried flutter_markdown today and stumbled upon the problem in the "Centered Header Demo" where the custom builder is not recognized. 

With this change the "Centered Header Demo" works as expected. I've added a basic description of the demo and included it in the demo application.

All the tests pass, but I'm not sure if this change introduces problems elsewhere.

### CODE REVIEW

**Comment by MarkusWendorf** [comment]
@googlebot I signed it!

**Comment by domesticmouse** [comment]
Hey @mjordan56, do you want to do a code review? =)

**Review by mjordan56 — APPROVED** [review]
@domesticmouse and @MarkusWendorf These changes look good to me. The changes to centered_header_demo.dart and home_screen.dart are valid and make the Center Header demo active in the examples project. These changes are good to have but are fairly benign in that the flutter markdown code isn't changed.

The more interesting changes are those being made to builder.dart as this is the code that implements the visitor pattern to walk the AST created by the Dart markdown package. The code that @MarkusWendorf is changing was introduced by @nobuhito in PR #241. I wasn't able to make sense of @nobuhito's code changes and preserved his changes when I made changes to the flutter markdown code. I agree with @MarkusWendorf that the code @nobuhito introduced doesn't appear to work. I commented the code in the hope that @nobuhito would see my comments and review the code and make the necessary changes. Since that hasn't happened, I reviewed the code changes in this PR by @MarkusWendorf and agree they make sense and are an improvement that should fix problems with supporting custom builders. I approve this PR.

**Comment by mjordan56** [comment]
Hi Brett,

I reviewed PR #299 and added my comments. As I mentioned in my comments in
the PR, the code MarkusWendorf is changing is code nobuhito introduced in
PR #241. It always looked wrong to me but I didn't have time to focus on it
and I was giving nobuhito an opportunity to review and fix his code. It's
been over 5 months since nobuhito introduced his PR. I agree with
MarkusWendorf that the code didn't appear to work and that
MarkusWendorf's changes are an improvement.

BTW, I haven't been active on flutter_markdown recently because I got a
Flutter contracting job that's been keeping me busy. I think about
flutter_markdown often and hope to return and contribute more in the future.

Michael

**Comment by domesticmouse** [comment]
Thanks @mjordan56 and @MarkusWendorf =)

**Review by domesticmouse — APPROVED** [review]

**Pull request merged**
