### PR TITLE
Add support for SVG images

### PR DESCRIPTION
**Pull request by ThinkDigitalSoftware**

### CODE REVIEW

**Comment by ThinkDigitalSoftware** [comment]
@googlebot I signed it!

**Comment by domesticmouse** [comment]
Can you please update this PR to fix the failing checks?

**Comment by ThinkDigitalSoftware** [comment]
@domesticmouse I don't believe I'm able to.
The failure message says:

> The current Flutter SDK version is 0.0.0-unknown.


Because flutter_markdown depends on flutter_svg >=0.0.2 which requires Flutter SDK version >=0.3.6 <2.0.0, version solving failed.

**Comment by domesticmouse** [comment]
@ThinkDigitalSoftware please try changing the `pubspec.yaml` environment clause to match `flutter_svg`:

```
environment:
  sdk: ">=2.2.0 <3.0.0"
  flutter: ">=1.5.9-pre.94 <2.0.0"
```

**Comment by ThinkDigitalSoftware** [comment]
@domesticmouse I fixed the issues, but I guess this PR is invalid with the most recent commit to master with the imageBuilder?

**Comment by domesticmouse** [comment]
Sorry @ThinkDigitalSoftware, I missed your question here. Is it worth fixing this PR up to the latest state of the world, or do you want to close it out?

**Comment by ThinkDigitalSoftware** [comment]
Honestly, it doesn't seem necessary, since it's a very specific fix to a single issue, vs the other option

**Pull request closed without merging**
