### PR TITLE
Add onTap handler to MarkdownBody when selectable is set to true.

### PR DESCRIPTION
**Pull request by slightfoot**

### CODE REVIEW

**Comment by slightfoot** [comment]
@domesticmouse Hey Brett, long time. Let me know if this needs more work or if it can be directly merged. Cheers.

**Comment by domesticmouse** [comment]
Hey Simon!

Any chance of adding some testing coverage? Untested functionality tends to break over time...

**Comment by domesticmouse** [comment]
Ping =)

**Comment by domesticmouse** [comment]
Hey @slightfoot, any chance of an update? =)

**Comment by slightfoot** [comment]
I'll look at this later on this evening.

**Comment by domesticmouse** [comment]
Hey @slightfoot, I'd really like to land this. Halp?

**Comment by domesticmouse** [comment]
Closing out as this was landed as part of #337

**Pull request closed without merging**
