### PR TITLE
HTML unescape URIs before passing to Image.network

### LINKED ISSUE #120: Network image URIs should be HTML-unescaped
If an image tag has query parameters, the `markdown` library will correctly HTML-escape `&` to `&amp;`.

When `flutter_markdown` then takes that URI and passes it to `Image.network`, it should unescape those ampersands. 

Not all web browsers will resolve escaped ampersands in the URI.

For example, the following input will result in an HTTP 403 instead of loading the image:

```markdown
here is an image:

![Image](https://preview.redd.it/sg3q5cuedod31.jpg?width=640&crop=smart&auto=webp&s=497e6295e0c0fc2ce7df5a324fe1acd7b5a5264f)
```

An image will be constructed using the raw HTML attribute `src`:

https://github.com/flutter/flutter_markdown/blob/0855cc0a6bc7fab3e60b76d1d9ea85bc1f00278d/lib/src/builder.dart#L235

Which will be (correctly) HTML escaped via

https://github.com/dart-lang/markdown/blob/bcda5112a1b001fe3cad8ac6c95ff6bc1f20cc56/lib/src/inline_parser.dart#L1030

The result is a call to `new Image.network` with the following uri:

```
https://preview.redd.it/sg3q5cuedod31.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=497e6295e0c0fc2ce7df5a324fe1acd7b5a5264f
```

Which results in an HTTP 403.

One possible fix is to call `Image.network` as follows:

```dart
child = new Image.network(uri.toString().replaceAll('&amp;', '&'), width: width, height: height);
```

### PR DESCRIPTION
**Pull request by orischwartz**
Fixes #120

### CODE REVIEW

**Comment by domesticmouse** [comment]
Can you please update this PR to fix the failing checks?

**Comment by orischwartz** [comment]
@domesticmouse Rebased against latest master and added a test.

Before the fix, test fails with the following:

```
  Expected:
'https://preview.redd.it/sg3q5cuedod31.jpg?width=640&crop=smart&auto=webp&s=497e6295e0c0fc2ce7df5a324fe1acd7b5a5264f'
  Actual:
'https://preview.redd.it/sg3q5cuedod31.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=497e6295e0c0fc2ce7df5a324fe1acd7b5a5264f'
```

**Comment by domesticmouse** [comment]
Thanks!

**Comment by KagurazakaHanabi** [comment]
Wait....it’s not a bug of flutter_markdown

**Comment by domesticmouse** [comment]
I'm happy to revert this PR, and/or mark the fixup as dependent on a markdown bug. Is there a fix in flight?

**Comment by KagurazakaHanabi** [comment]
https://github.com/dart-lang/markdown/commit/73f9db9fb18ddf4b535e78697dc0cee6f7309f49 It’s merged

**Pull request merged**
