### PR TITLE
Allow custom bullet points through a widget builder

### PR DESCRIPTION
**Pull request by SKLn-Rad**
Just a small feature I needed for a project I am working on. Might be something of value to other users!

Tests updated and passing.
Version bumped to 0.6.1 to indicate feature addition.
Builder included in both Markdown and MarkdownBody

### CODE REVIEW

**Comment by SKLn-Rad** [comment]
@googlebot I signed it!

**Comment by SKLn-Rad** [comment]
Tests seem flaky? Pass 100% of the time on my machine (running stable) so might be worth pulling down on your end.

**Comment by domesticmouse** [comment]
@RedBrogdon any hints on who I should hassle about compilers being sad on Cirrus? 

```
00:00 +0 -1: loading /tmp/cirrus-ci-build/test/flutter_markdown_test.dart [E]                                                                                                                          
  Exception: the Dart compiler exited unexpectedly.
  package:flutter_tools/src/base/common.dart 28:3               throwToolExit
  package:flutter_tools/src/compile.dart 705:13                 DefaultResidentCompiler._compile.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/stream_impl.dart 392:13                            _BufferingStreamSubscription._sendDone.sendDone
  dart:async/stream_impl.dart 402:15                            _BufferingStreamSubscription._sendDone
  dart:async/stream_impl.dart 286:7                             _BufferingStreamSubscription._close
  dart:async/stream_transformers.dart 98:11                     _SinkTransformerStreamSubscription._close
  dart:async/stream_transformers.dart 25:11                     _EventSinkWrapper.close
  dart:convert/string_conversion.dart 251:11                    _StringAdapterSink.close
  dart:convert/line_splitter.dart 136:11                        _LineSplitterSink.close
  dart:async/stream_transformers.dart 143:24                    _SinkTransformerStreamSubscription._handleDone
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
```

**Comment by domesticmouse** [comment]
Okiday, I don't know what changed, but poking the Cirrus bot a couple of times made the tests actually pass. Can you resolve the conflicts on this PR so I can merge it?

**Comment by domesticmouse** [comment]
@SKLn-Rad Please update and resolve conflicts, so I can land this PR.

**Comment by SKLn-Rad** [comment]
Sorry its been literally over a year! Been under heavy NDA so all dependencies on main line work have been frozen.
I've updated this inline with null safety and fixed the test.

Also apologies for the dart settings formatting everything! I have my dart.lineLength set to 200 for my monitor :)

**Review by domesticmouse — APPROVED** [review]

**Comment by domesticmouse** [comment]
thanks!

**Pull request merged**
