### PR TITLE
Add strikethrough support

### LINKED ISSUE #104: Run Markdown example
Hi,

I want to try this out, but I am confused on how to run the example provided.
Why is there just one file as an example?

I know this from other packages, that there are all files needed to run this example directly:
https://github.com/flutter/packages/tree/master/packages/palette_generator/example
https://github.com/flutter/packages/tree/master/packages/palette_generator/example
https://github.com/flutter/plugins/tree/master/packages/cloud_firestore/example

I want to give this #19 a shot.

### LINKED ISSUE #131: Support Strikethrough?
```
~~text~~
```

~~text~~

### PR DESCRIPTION
**Pull request by KagurazakaHanabi**
## Related Issues
Closes #131
Closes #104

### CODE REVIEW

**Comment by KagurazakaHanabi** [comment]
@googlebot I signed it!

**Comment by domesticmouse** [comment]
Can you please add a test for the new ~~strikethrough~~ case?

**Comment by KagurazakaHanabi** [comment]
Done it

**Comment by domesticmouse** [comment]
Thank you for the PR!

**Pull request merged**
