### PR TITLE
Render certain tags by user

### LINKED ISSUE #144: Add ability to render certain tags ourselves
I would like to be passed a Markdown "element" if I choose for rendering myself. Sometimes the stylesheet isn't enough. For example, I want to use a Flutter Widget that includes syntax highlighting for dart. I tried using their syntax highlighter class with this library, but it was riddled with errors. If we have a parameter for that, it would add a lot of flexibility. Or if the code for rendering each element was broken out into individual overridable functions for those extending the class, we could effectively accomplish the same thing

### PR DESCRIPTION
**Pull request by KagurazakaHanabi**
And apply textScaleFactor automatically https://github.com/flutter/flutter_markdown/issues/95#issuecomment-559012243

## Related issue
Closes #144 

cc @domesticmouse @ThinkDigitalSoftware @ened

### CODE REVIEW

**Comment by ThinkDigitalSoftware** [comment]
Thank you!

**Comment by KagurazakaHanabi** [comment]
@ThinkDigitalSoftware What do you think about this API design?

**Comment by ThinkDigitalSoftware** [comment]
To be honest, I don't understand it. I see this in the code, but it don't see how to use it.
```
## Custom Syntax
NaOH + Al_2O_3 = NaAlO_2 + H_2O
C_4H_10 = C_2H_6 + C_2H_4
## Markdown widget
This is an example of how to create your own Markdown widget:
    Markdown(data: 'Hello _world_!');
Enjoy!
[Google]: https://www.google.com/

**Comment by ThinkDigitalSoftware** [comment]
What I was expecting was something like this. I'll use HTML as an example cause it's easy.
if the source pseudo-code was 
```html
<listItem> item1</listItem>
```

then I would be able to provide a callback to the builder to look for those tags. Like a preprocessor.
I would write, 
```dart
customBuilder: (String tag, String data){
    if(tag == 'listItem'){ // or if there's an enum or something, I could use that
        return Text(data, style: TextStyle(fontWeight: FontWeight.bold));
    }

**Comment by KagurazakaHanabi** [comment]
```
class CustomBuilder implements MarkdownElementBuilder {
   @override
   Widget visitElementAfter(md.Element element) {
        return Text(element.textContent, style: TextStyle(fontWeight: FontWeight.bold));
    }
 }
```

then add this builder to Map:

```
Markdown(
    data: _markdownData,
    builders: {
        'listItem': CustomBuilder(),
    }
)
```

**Comment by ThinkDigitalSoftware** [comment]
Looks good to me!

**Comment by KagurazakaHanabi** [comment]
> To be honest, I don't understand it. I see this in the code, but it don't see how to use it.

The `H_2O` is a custom syntax, it will be parse as `H<sub>2</sub>O`, then the `sub` tag will parse by `builders['sub']`

**Comment by KagurazakaHanabi** [comment]
@ThinkDigitalSoftware I found a problem, the html in markdown cannot be parsed to AST, so it can only be used with custom syntax

**Comment by ThinkDigitalSoftware** [comment]
I wish I had more experience with this to understand what that means

**Comment by ened** [comment]
@KagurazakaHanabi can you please move https://github.com/flutter/flutter_markdown/pull/157/commits/f47caf186d923172c99b8d18bfdd34dc71240f08 into a separate PR and as a minor version bump + changelog update. 

Also, I think this will need a test.

**Comment by ened** [comment]
@KagurazakaHanabi And, thank you very much for addressing the issue!

**Pull request closed without merging**
